baseURL = 'https://terminal.agast.net/'
languageCode = 'en-us'
title = 'Andrew Gast | CyberSecurity'
theme = "terminal"


[params]
# Load Custom Colour File
	customCSS = ["css/terminal.css"]
	favicon = "favicon.png"
	images = ["og-image.png"
